spring.application.name=printflow
server.port=3000
spring.datasource.url=jdbc:postgresql://200.18.128.54:5432/ra0081809
spring.datasource.username=ra0081809
spring.datasource.password=Hemy0306
spring.datasource.driver-class-name=org.postgresql.Driver

spring.profiles.active=${ACTIVE_PROFILE:dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=404D86E10A58B6F920240F2035E953420A9B1E9121A875B8FF687F830DF4F191